{{- range .Values.devicePairs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .bDevice }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ $.Values.pvc.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .rDevice }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ $.Values.pvc.storageClass }}
{{- end }}
